config/routes.rb
Rails.application.routes.draw do

  get 'pratice_page2/test'

  resources :articles do
    resources :comments
  end

  resources :practice

  root 'home#index'
  
  match 'home' => 'home#index', :via => :get
  match 'findid' => 'practice#findid', :via => :get
  match 'signup' => 'practice#signup', :via => :get

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	
	#http_basic_authenticate_with name: "jihun", password: "access123", except: [:index, :show]

	def new
		@article = Article.new
	end

	def edit
		@article = Article.find(params[:id])
	end

	def create
		@article = Article.new(article_params)
		
		if @article.save
		  redirect_to @article
		else
		  render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def index
		@articles = Article.all
	end

	def update
	  @article = Article.find(params[:id])
	 
	  if @article.update(article_params)
	    redirect_to @article
	  else
	    render 'edit'
	  end
	end

	def destroy
	  @article = Article.find(params[:id])
	  @article.destroy
	 
	  redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :text)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  #http_basic_authenticate_with name: "jihun", password: "access123", except: [:index, :show]

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
	def new
	end

	def findid
	end

	def signup
	end

	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %>|</td>
      <td><%= link_to 'Edit', edit_article_path(article) %>|</td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Main', controller: 'home' %>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/home/index.html.erb
<%= stylesheet_link_tag "home.scss"%>

<div id="test">
	<h1>Jihun's RubyOnRails Practice</h1>
</div>
<%= link_to 'First_Pratice', controller: 'articles' %><br>
<%= link_to 'Second_Pratice', controller: 'practice' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Practice1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/practice/findid.html.erb
<%= stylesheet_link_tag "practice.scss"%>

<div id="wrap">
  <div id="header-region"><div><div id="header">
  <div id="header-section1">
    <div id="header-section1-main" class="navbar navbar-inverse">
      <div id="header-log" class="pull-left">
        <div class="navbar-header">
          <a class="navbar-brand pull-left" href="practice">
            <img src="/images/biz_korean.png">
            <span><font size="1"> (시범서비스)</font></span>
            <span><font size="2" color="red"></font></span>
          </a>
        </div>
      </div>
      <div class="header-menu2">
        <div id="header-menu2-region" class="pull-right"><div><ul class="nav navbar-nav"><li id="menu-signin"><a href="#/signin">로그인</a>
</li><li id="menu-signup"><a href="signup">회원가입</a>
</li></ul>
</div></div>
      </div>
    </div>
  </div>
  <div id="header-section2">
    <div id="header-section2-main" class="header-menu1">
      <div id="header-menu1-region" class="pull-left"><div><ul class="nav navbar-nav"><li id="menu-productions"><a href="#/productions">상품소개</a>
</li></ul>
</div></div>
    </div>
  </div>
</div>
</div></div>
  <div id="main-region"><div>
  <div id="findidpw">
  <div class="row">
    <div id="menu-region" class="col-sm-2">
    <div id="findidpw_menu">
    <div id="menu"> <div class="title">회원 가입</div> <div class="list-group"><div><a href="signup" class="list-group-item">회원가입</a></div><div>
    <a href="findid" class="list-group-item active">아이디 / 비밀번호 확인</a>
    </div>
    </div>
    </div>
    </div>
    </div>
	<div id="service-region" class="col-sm-10">
	  <div>
	    <div id="header-title">아이디 / 비밀번호 확인</div>
	    <div class="subtitle">
		  <img src="/images/id_key.png">
			회원님의 이메일 주소를 입력해 주시면 해당 이메일로 아이디/비밀번호 정보를 보내드립니다.
		</div>
		<div id="findidpw_service_region">
    <div>
    <div id="findidpw">
     <div class="row">
       <div class="col-sm-6">
        <div id="findid-region"><div><h3><b>아이디 찾기</b></h3>
<div class="findidpw_description">회원님의 <b>전화번호</b>를 입력해주세요.</div>
<br><br>
<form>
  <div class="findidpw_input_area">
    <input class="findidpw_input type-only-numbers invalid" type="text" name="cellphone" data-validation="cellphone" placeholder="휴대전화번호를 입력하세요" autofocus="">
    <font class="error_msg" color="red" size="2">필수 입력 항목입니다.</font>
  </div>
  <div>   
    <span class="loading" style="display: none;">요청중</span>
    <input id="validation_submit" class="btn btn-primary" type="submit" value="확인" style="display: inline-block;">
  </div>
</form>



</div></div>
      </div>
      <div class="col-sm-6">
         <div id="findpw-region"><div><h3><b>비밀번호 초기화</b></h3>
<div class="findidpw_description">회원님의 <b>이메일 주소</b>와 <b>전화번호</b>를 입력하시면 해당 이메일로 임시 비밀번호를 보내드립니다.</div>
<br>
<form>
  <div class="findidpw_input_area">
    <input class="findidpw_input" type="text" name="findpw_email" data-validation="findpw_email" placeholder="아이디를 입력하세요" autofocus="">
    <font class="error_msg" color="red" size="2"> Email 주소를 입력해주세요.</font>
  </div>
  <div class="findidpw_input_area">
    <input class="findidpw_input type-only-numbers" type="text" name="findpw_cellphone" data-validation="findpw_cellphone" placeholder="휴대전화번호를 입력하세요" autofocus="">
    <font class="error_msg" color="red" size="2"> [missing "ko.ui.findidpw.error_input_cellphone" translation]</font>
  </div>
  <div>
    <span class="loading" style="display: none;">요청중</span>
    <input id="validation_submit" class="btn btn-primary" type="submit" value="확인" style="display: inline-block;">
  </div>
</form>



</div></div>
       </div>
     </div>

<div>
</div></div></div></div>
	  </div>
	</div>
  </div>
</div>
</div></div>
  <div id="dialog-region"></div>
  <div id="push"></div>
</div>

<div id="footer-region"><div><div id="footer">
  <div id="footer-ktlogo" class="pull-left">
      <img src="/images/ktlogo.png">
    </div>
  <div class="row">
    <div id="footer-link" class="col-sm-8">
      <a href="http://www.kt.com/main.jsp" target="_blank" class="link_info">회사소개 </a>
      <span>/</span>
      <a href="http://www.kt.com/eng/main.jsp" target="_blank" class="link_info"> ENGLISH</a>
      <a href="http://inside.olleh.com/html/infoView.asp?code=HBA00&amp;sub=02&amp;LnbCode=AC0" class="link_info">이용약관</a>
      <a href="http://inside.olleh.com/html/infoView.asp?code=HC000" class="link_info">법적고지</a>
      <a href="http://inside.olleh.com/html/infoView.asp?code=HD000" class="link_info">개인정보취급방식</a>
      <a href="http://inside.olleh.com/html/infoView.asp?code=HE000" class="link_info">청소년 보호정책</a>
      <a href="http://help.olleh.com/pc/service/appcenter/MobileCenter.jsp" class="link_info">문의/안내처</a>
      <a href="http://www.olleh.com/html/WebAccessibility/Info.asp" class="link_info">웹접근성 도움말</a>
      <div id="info">
        <span>(주)케이티 대표이사 황창규</span>
        <span>&nbsp;&nbsp;&nbsp;사업자등록번호 : 102-81-42945
        </span><span>&nbsp;&nbsp;&nbsp;통신판매업신고 : 2002-경기성남-0048</span><br>
        <span>주소 : 463-711 경기도 성남시 분당구 불정로 90 (정자동 206번지)</span>
        <span>&nbsp;&nbsp;&nbsp;TEL : 국번없이 100</span><br>
        <span>Copyright ⓒ2015 kt corp. All rights reserved.
      </span></div>
    </div>

    <div id="help-desk" class="col-sm-4">
      <div class="line1 row">
        <div class="col-sm-12">고객지원센터정보</div>
      </div>
      <div class="line2 row">
        <div class="col-sm-3">
          <img src="/images/img_icon_4.png">
        </div>
        <div class="col-sm-9">
          <span>Tel. <span class="span-red">080-2580-007</span></span><br>
          <span>평일: 09:00 ~ 18:00</span>
          <span>/토요일: 09:00 ~ 13:00</span><br>
          <span>(일, 공휴일 휴무 입니다)</span><br>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- release version -->
<span style="font-size:x-small; font-style: italic; margin:0; color:white;">ver 0.3.4</span>
</div></div>

app/views/practice/index.html.erb
<h1> UI Practice </h1>
<%= link_to 'Home', controller: 'home' %> |
<%= link_to 'New', new_practice_path %> |
<%= link_to 'SignUp', '/signup' %> |
<%= link_to 'FindID', '/findid' %>

app/views/practice/new.html.erb
<h1> practice !! </h1>
<%= link_to 'Back', controller: 'practice' %>